/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './router/__root'
import { Route as ResumeRouteImport } from './router/resume'
import { Route as ProjectRouteRouteImport } from './router/project/route'
import { Route as IndexRouteImport } from './router/index'
import { Route as ProjectIndexRouteImport } from './router/project/index'
import { Route as ProjectTodoIndexRouteImport } from './router/project/todo/index'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectTodoIndexRoute = ProjectTodoIndexRouteImport.update({
  id: '/todo/',
  path: '/todo/',
  getParentRoute: () => ProjectRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project': typeof ProjectRouteRouteWithChildren
  '/resume': typeof ResumeRoute
  '/project/': typeof ProjectIndexRoute
  '/project/todo/': typeof ProjectTodoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/project': typeof ProjectIndexRoute
  '/project/todo': typeof ProjectTodoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project': typeof ProjectRouteRouteWithChildren
  '/resume': typeof ResumeRoute
  '/project/': typeof ProjectIndexRoute
  '/project/todo/': typeof ProjectTodoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/project' | '/resume' | '/project/' | '/project/todo/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/resume' | '/project' | '/project/todo'
  id: '__root__' | '/' | '/project' | '/resume' | '/project/' | '/project/todo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  ResumeRoute: typeof ResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/todo/': {
      id: '/project/todo/'
      path: '/todo'
      fullPath: '/project/todo/'
      preLoaderRoute: typeof ProjectTodoIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
  }
}

interface ProjectRouteRouteChildren {
  ProjectIndexRoute: typeof ProjectIndexRoute
  ProjectTodoIndexRoute: typeof ProjectTodoIndexRoute
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectIndexRoute: ProjectIndexRoute,
  ProjectTodoIndexRoute: ProjectTodoIndexRoute,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  ResumeRoute: ResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
